### ISSUE TITLE
i hope to see a great guide for this package

### ISSUE THREAD

**Issue by gok-wolf** [adamlilith/enmSdmPredImport#12]
i hope to see a great guide for this package like that
http://www.earthskysea.org/best-practices-in-species-distribution-modeling-a-workshop-in-r/
thanks in advance...

**Comment by adamlilith** [comment]
Sorry, for the delay!  Yes, I'll try to get something like a guide for this together.  A vignette would probably work best. Thanks for the idea!

**Comment by gok-wolf** [comment]
thank you and be sure your works are the best!
